/**
 * YouTube Transcript Extractor — Node.js Example
 *
 * Extract transcripts from videos, playlists, or channels. No API key required.
 * Get your API token at: https://console.apify.com/settings/integrations
 */
import { ApifyClient } from 'apify-client';

const client = new ApifyClient({ token: 'YOUR_API_TOKEN' });

const run = await client.actor('george.the.developer/youtube-transcript-scraper').call({
    urls: [
        'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        'https://www.youtube.com/playlist?list=PLrAXtmErZgOeiKm4sgNOknGvNjby9efdf',
    ],
    language: 'en',
    outputFormat: 'full-text',   // full-text, segments, or both
    includeMetadata: true,
    maxVideos: 50,
});

const { items } = await client.dataset(run.defaultDatasetId).listItems();

items.forEach(video => {
    console.log(`${video.title} (${video.wordCount} words)`);
    console.log(`  Language: ${video.language} (auto: ${video.isAutoGenerated})`);
    console.log(`  Preview: ${video.transcriptText?.substring(0, 150)}...\n`);
});
